apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  dev-config.json:
    '{
      "datasource.url": "jdbc:mysql://localhost:3306/otp?autoReconnect=true&useUnicode=true&characterEncoding=utf8",
      "datasource.username": "root",
      "datasource.password": "root"
     }'
  stg-config.json:
    '{
        "example.datasource.url": "jdbc:mysql://stg-endpoint/example",
        "example.datasource.username": "stg-root",
        "example.datasource.password": "stg-pass"
       }'