apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-demo
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-demo
  template:
    metadata:
      labels:
        app: config-demo
    spec:
      containers:
        - name: config-demo
          image: registry.evampsaanga.com/test/exppoc:7
          resources:
            limits:
              cpu: 1
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: dev-config.json
      imagePullSecrets:
        - name: harbor

---
apiVersion: v1
kind: Service
metadata:
  name: config-demo
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: config-demo
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "externaldb"
spec:
  ports:
    - name: "mysql"
      protocol: "TCP"
      port: 3306
      targetPort: 3306
      nodePort: 0
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "externaldb"
subsets:
  - addresses:
      - ip: "192.168.10.100"
    ports:
      - port: 3306
        name: "mysql"
